lib/build/filter-build-output.rb: The sawError variable has been unused since the first revision of this file.  I seem to be returning failure based on the child's exit status.  That's superior to screen-scraping anyhow.  Ruby 1.9 complained:
/home/martind/software.jessies.org/nightlies/salma-hayek/lib/build/filter-build-output.rb:60: warning: assigned but unused variable - sawError

lib/build/universal.make: Ruby 1.9 complained about my perlish free invocation of chomp!():

-e:1:in `<main>': undefined method `chomp!' for main:Object (NoMethodError)

Surely I need to apply that to the perlish line noise that is $_.